### ISSUE TITLE
Batch里面的任务一直卡在runnable状态

### ISSUE THREAD

**Issue by sunl** [awslabs/spot-tagging-bot-for-digital-assets#1]
通过在API Gateway控制台 测试情感分析机器人，

Batch里面的计算环境用的是spot，optimal：
![spot-issue-1](https://user-images.githubusercontent.com/4168127/91943860-d15cff00-ed2f-11ea-87d2-58190b3cc89a.jpeg)
实际起的机器是c4.xlarge, 4核7680M内存：
![spot-issue-2](https://user-images.githubusercontent.com/4168127/91943872-d4f08600-ed2f-11ea-893a-07c87c5ef311.png)
但是作业定义要求的是4核,8096M内存：
![spot-issue-3](https://user-images.githubusercontent.com/4168127/91943874-d5891c80-ed2f-11ea-828e-47899591e808.jpeg)
所以资源是不够的，导致作业一直卡在runnable状态：
![spot-issue-4](https://user-images.githubusercontent.com/4168127/91943875-d621b300-ed2f-11ea-9eb4-821d737b9d1e.png)

**Comment by dashjim** [comment]
Hello @sunl 

I think there are some options to resolve it:
* A *quick fix* would be to temporarily increase the minimum vCPUs from 8 to 32 in AWS Batch Compute Environment. 
> But be aware that there is no way to reduce the vCPU back unless you delete the `compute environment`.
* A code level fix would be to reduce the minimum vCPU to 0 - this ensures the Batch only provision the instance upon receiving a job. And it will select the most appropriate instance type which meets the job definition. As is described in the console -
> Allowed instance types
> *optimal*
> Jobs define their vCPU and memory requirements at submission and that information is used to match the job with the most appropriately sized instance.

This kind of fix will increase the processing time for the first job. Because the instance is provisioned the at the time job is coming. 
* We can also specify one specific instance type as well.

**Comment by dashjim** [comment]
Closed - It is fixed by allow change in task memory and CPU in Dynomodb.
